---
title: "Website Interactive"
author: "J Andres Gannon and Natalie Seaton Gold"
date: "2021-09-27"
output:
  html_notebook:
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
  html_document:
    toc: yes
editor_options:
  chunk_output_type: inline
---
<style>
    body .main-container {
        max-width: 100%;
    }
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set up
```{r}
library(googlesites)
options(googlesites.site_domain = "https://sites.google.com/view/militarycapabilities/")

library(googleAuthR)
options(googleAuthR.client_id = getOption("googlesites.client_id"))
options(googleAuthR.client_secret = getOption("googlesites.client_secret"))
options(googleAuthR.scopes.selected = "https://sites.google.com/feeds/")
gar_auth()
```

# Visualization page
```{r}
test_html <- system.file("extdata", "example-site", "test.html", package = "googlesites")
add_html_page(page_xhtml_source = test_html,
              page_title = 'API Test',
              page_custom_url = 'api-test',
              overwrite = TRUE)
```
