---
title: '\singlespacing Planes, Trains, and Armored Mobiles: Introducing a Dataset of the Global Distribution of Military Capabilities (rDMC)'
author:
  - name: J Andrés Gannon
    email: "juan.gannon@vanderbilt.edu"
    url: jandresgannon.com
    affiliation: Vanderbilt University
date: "`r format(Sys.Date(), '%B %d, %Y')`"
format:
  pdf:
    fig-format: jpeg
    thanks: All data and code are publicly available at https://www.militarycapabilities.com/
    number-sections: true
    fontsize: "12"
  docx:
    fig-format: jpeg
    fig-dpi: 600
    thanks: All data and code are publicly available at https://www.militarycapabilities.com/
execute:
  echo: false
  warning: false
  cache: true
abstract: \singlespacing \noindent 
header-includes:
- \usepackage{tikz}
- \usepackage{pgfplots}
- \pgfplotsset{compat=newest}
- \usetikzlibrary{plotmarks}
- \usetikzlibrary{arrows.meta}
- \usepgfplotslibrary{patchplots}
- \usepackage{grffile}
- \usepackage{caption}
- \usepackage[utf8]{inputenc}
- \usepackage[doublespacing]{setspace}
- \usepackage{float}
- \usepackage{multirow}
- \renewcommand{\topfraction}{.85}
- \renewcommand{\bottomfraction}{.7}
- \renewcommand{\textfraction}{.15}
- \renewcommand{\floatpagefraction}{.66}
- \setcounter{topnumber}{3}
- \setcounter{bottomnumber}{3}
- \setcounter{totalnumber}{4}
bibliography: rDMC-bib.bib
---

```{r knitr_options, cache = FALSE, message = FALSE}
# added to indicate that the home folder is the repo folder
library(knitr)
library(ggplot2)
library(ggtext)
library(ggrepel)
knitr::opts_knit$set(root.dir = normalizePath(here::here()))
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      error = FALSE, 
                      message = FALSE, 
                      fig.path = "figures/")
```

```{r load data}

```

\newpage


